params:
  cuda_devices: [] #[0]

optional_plugin_components: {}
#optional_plugin_components:
# cuda_device_monitor:
#   template: openfl.plugins.processing_units_monitor.pynvml_monitor.PynvmlCUDADeviceMonitor
#   settings: []

shard_descriptor:
  template: victim_shard_descriptor.MnistShardDescriptor
  params:
    rank_worldsize: 2, 3
